/**
 * 12-0 ratings audit — writes docs/RATINGS_AUDIT.md from public/data/players.json.
 *
 * The doc has two parts:
 *   1. A hand-maintained ANALYSIS header (problems found, formula changes, known off-cases,
 *      suggestions) — edit the ANALYSIS constant below to keep it current.
 *   2. Auto-generated tables (Top 100 by OVR + every current/2020s player), regenerated from the
 *      live data each run so the numbers never go stale.
 *
 * Run:  npx tsx scripts/data/audit.ts   (or `npm run data:audit`)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { OUT_DIR, ROOT } from './util.ts';

interface Player {
  id: string;
  name: string;
  positions: string[];
  teams: { franchise: string; decades: string[] }[];
  peakSeason?: string;
  ratings: Record<string, number>;
  height?: string;
}
interface Franchise { id: string; abbreviation: string }

const players = JSON.parse(readFileSync(join(OUT_DIR, 'players.json'), 'utf8')) as Player[];
const franchises = JSON.parse(readFileSync(join(OUT_DIR, 'franchises.json'), 'utf8')) as Franchise[];
const fabbr = new Map(franchises.map((f) => [f.id, f.abbreviation]));

const W: Record<string, number> = {
  shooting: 0.2, playmaking: 0.15, defense: 0.15, clutch: 0.15,
  athleticism: 0.1, rebounding: 0.1, height: 0.08, basketballIq: 0.07,
};
const ovr = (r: Record<string, number>) => Math.round(Object.entries(W).reduce((a, [k, w]) => a + r[k] * w, 0));
const CATS = ['shooting', 'playmaking', 'defense', 'clutch', 'athleticism', 'rebounding', 'height', 'basketballIq', 'durability'];
const HDR = ['SHO', 'PLY', 'DEF', 'CLU', 'ATH', 'REB', 'HGT', 'IQ', 'DUR'];

const withOvr = players.map((p) => ({ ...p, _ovr: ovr(p.ratings) }));
const sorted = [...withOvr].sort((a, b) => b._ovr - a._ovr);
const top100 = sorted.slice(0, 100);
const top100ids = new Set(top100.map((p) => p.id));
const current = withOvr.filter((p) => p.teams.some((t) => t.decades.includes('2020s'))).sort((a, b) => b._ovr - a._ovr);

const teamLabel = (p: Player) => {
  const t = [...p.teams].sort((a, b) => b.decades.length - a.decades.length)[0];
  return t ? `${fabbr.get(t.franchise) ?? t.franchise} ${t.decades.join('/')}` : '—';
};

const ANALYSIS = `# Ratings Audit — analysis, changelog & player tables

> Generated by \`scripts/data/audit.ts\` (\`npm run data:audit\`). The tables are rebuilt from
> \`public/data/players.json\`; the analysis below is hand-maintained in the script. **${players.length}** players total.

**Columns:** OVR = weighted sum of the 8 OVR categories. SHO Shooting · PLY Playmaking · DEF Defense ·
CLU Clutch · ATH Athleticism · REB Rebounding · HGT Height rating · IQ Basketball IQ · DUR Durability
(not in OVR). "Height" = listed height.
**OVR weights:** Shooting .20 · Playmaking .15 · Defense .15 · Clutch .15 · Athleticism .10 ·
Rebounding .10 · Height .08 · IQ .07.

---

## 1. The problem (original model)

Ratings are derived from real box-score data, percentile-ranked **within each player's peak decade**,
then mapped to 0-99. The first version had three systemic faults:

1. **Severe OVR compression.** The entire top 100 spanned only ~89 → 81 (an 8-point band) and the
   single highest OVR in the whole database was 89. There was no headroom to separate an all-time
   great from a good starter — Jordan, LeBron and Curry all sat in the mid-80s alongside role players.
2. **Thin-era inflation.** Because ratings were percentile-ranked *within a decade*, a top-of-era
   player in the shallow, stat-inflated 1960s–70s leagues scored as high as a top-of-era star today.
   Versatile old bigs rocketed up — **Alvan Adams ranked #4 all-time**, above Jordan/LeBron/Curry,
   with Rich Kelley, Larry Kenon, Bob Lanier and Mickey Johnson all in the top ~35.
3. **Modern creators suppressed.** Trae Young (75, #583), Ja Morant, SGA, Tatum and Luka all landed
   *below* 1970s role players. Box-score steals/blocks ≠ defense and the height map penalizes guards,
   so perimeter creators got dragged down by DEF / ATH / HGT / REB.

The career-average representative line also diluted the durable greats (Kareem/Kobe/LeBron) with their
long rookie + decline tails, pushing their numbers down.

## 2. What changed (\`scripts/data/build.ts\`)

1. **Prime-weighted stats.** Token/rookie/decline seasons (< half a player's peak-minutes season) are
   dropped and the biggest seasons are emphasised (minutes^1.3). Ratings now reflect a player's
   *prime*, like 2K — durable greats stop being diluted by long tails.
2. **Star-separating curve.** \`rate(p) = clamp(round(36 + 63·p^1.25), 25, 99)\`. The ceiling rose
   95 → 99 (so all-time greats can reach the top of the scale) and the convex shape (exponent > 1)
   makes the elite pull away from the merely-good instead of bunching in the 80s.
3. **Era-strength discount** (skill ratings only — **not** height or durability): a points haircut by
   peak decade — \`1940s −6, 1950s −4.5, 1960s −3, 1970s −4, 1980s −1.5, 1990s −0.5, 2000s+ 0\`.
   Percentile-within-decade otherwise treats a shallow old league as equal to today's far deeper one;
   true greats sit high enough in their era to survive the haircut, role players fall to where they
   belong. Height (a 7-footer is 7 feet in any era) and durability (era-neutral longevity) are exempt.

**Effect:** top-50 is now spread across every decade (≈ 2010s 13, 2000s 10, 1990s 7, 1980s 5, 1970s 6,
1960s 4, 2020s 5). Alvan Adams fell #4 → #22. Signature traits pop correctly — Curry 97 SHO / 98 CLU,
Magic 98 PLY, Wilt 96 ATH / 94 REB, Westbrook & Luka 99 PLY, Reggie 95 SHO, Gobert 98 DEF.

## 3. Known remaining off-cases (candidates for a 2K override pass)

These are the limits of a box-score model under the **locked OVR weights** — best fixed with a curated
2K-derived override list rather than more formula tuning:

- **Karl-Anthony Towns too high (≈ #3).** The defense proxy (steals + blocks + rebound %) and the
  clutch proxy (points + TS% + usage) both over-reward high-usage stretch bigs. Same effect inflates
  Embiid's and Gobert's DEF.
- **Non-shooting bigs a touch low** — Wilt, Kareem, Shaq, Duncan. The .20 shooting weight (built from
  FT% / 3P% / efficiency) punishes career poor free-throw shooters even when they were dominant.
- **Bill Russell broken (≈ #1261).** His entire value was defense, rebounding and winning; pre-1974
  there are no steals/blocks, his scoring/FT% were low, and rings aren't in the box score. Pure
  override case.
- **Trae Young / small score-first guards low.** With the locked weights, four categories (DEF, REB,
  HGT, ATH) at 55-65 cap a defensively-limited 6'1" guard around 73-78, regardless of elite
  shooting/playmaking. 2K rates these players higher via position-relative weighting.

## 4. Suggestions

- **2K override list (highest leverage).** Provide name → 9 category values for the marquee tier
  (top ~100 + current stars). Layered last in \`data-source/curated/overrides.json\`, absolute values
  bypass the formula and curve entirely. Start with the off-cases in §3.
- **Athleticism & Clutch are the weakest proxies** (box stats barely capture them). 2K's
  speed/vertical/clutch attributes would be the most valuable external data to import here.
- **Defense** is similarly limited — steals + blocks over-reward bigs and miss perimeter stoppers; a
  2K defense/perimeter-D value would help most.
- **Consider position-relative OVR weighting** (long-term, if the locked weights are ever revisited):
  weighting playmaking/shooting more for guards and rebounding/height more for bigs would lift
  score-first guards (Trae, Booker) without distorting bigs — closest to how 2K computes overall.
- **Re-tune the era discount** if the 2K list shifts the balance; it's a single \`ERA_PEN\` table in
  \`build.ts\`.

---

`;

const colHead = `| # | Name | Pos | Team (era) | Peak | OVR | ${HDR.join(' | ')} | Height |`;
const colSep = `|---|------|-----|-----------|------|-----|${HDR.map(() => '---').join('|')}|--------|`;
const row = (p: typeof withOvr[number], rank: number, flag = '') =>
  `| ${rank} |${flag ? ` ${flag} |` : ''} ${p.name} | ${p.positions.join('/')} | ${teamLabel(p)} | ${p.peakSeason ?? '—'} | **${p._ovr}** | ${CATS.map((c) => p.ratings[c]).join(' | ')} | ${p.height ?? '—'} |`;

let out = ANALYSIS;
out += `## A. Top 100 by OVR\n\n${colHead}\n${colSep}\n`;
out += top100.map((p, i) => row(p, i + 1)).join('\n');
out += `\n\n## B. Current players (any 2020s stint), by OVR\n\n`;
out += `⚠️ = **not** in the global Top 100 above — i.e. current stars the model may rate too low.\n\n`;
out += `${colHead.replace('| # |', '| # | ⚠ |')}\n${colSep.replace('|---|', '|---|---|')}\n`;
out += current.map((p, i) => row(p, i + 1, top100ids.has(p.id) ? '' : '⚠️')).join('\n');
out += '\n';

writeFileSync(join(ROOT, 'docs', 'RATINGS_AUDIT.md'), out);
console.log(`wrote docs/RATINGS_AUDIT.md — top100 OVR ${top100[0]._ovr}→${top100[99]._ovr}, ${current.length} current players`);
